package mypojos;
// Generated Aug 12, 2019 9:07:05 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Dailysales generated by hbm2java
 */
public class Dailysales  implements java.io.Serializable {


     private Integer iddailysales;
     private Integer fueltyp;
     private Double expence;
     private Double revenue;
     private Double total;
     private Date datesl;

    public Dailysales() {
    }

    public Dailysales(Integer fueltyp, Double expence, Double revenue, Double total, Date datesl) {
       this.fueltyp = fueltyp;
       this.expence = expence;
       this.revenue = revenue;
       this.total = total;
       this.datesl = datesl;
    }
   
    public Integer getIddailysales() {
        return this.iddailysales;
    }
    
    public void setIddailysales(Integer iddailysales) {
        this.iddailysales = iddailysales;
    }
    public Integer getFueltyp() {
        return this.fueltyp;
    }
    
    public void setFueltyp(Integer fueltyp) {
        this.fueltyp = fueltyp;
    }
    public Double getExpence() {
        return this.expence;
    }
    
    public void setExpence(Double expence) {
        this.expence = expence;
    }
    public Double getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(Double revenue) {
        this.revenue = revenue;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getDatesl() {
        return this.datesl;
    }
    
    public void setDatesl(Date datesl) {
        this.datesl = datesl;
    }




}


