package mypojos;
// Generated Aug 12, 2019 9:07:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Fuelstock generated by hbm2java
 */
public class Fuelstock  implements java.io.Serializable {


     private Integer idfuel;
     private Integer fueltype;
     private Double unitprice;
     private Double currentqty;
     private Integer status;
     private Set fuelstockHasUsers = new HashSet(0);
     private Set invoices = new HashSet(0);

    public Fuelstock() {
    }

    public Fuelstock(Integer fueltype, Double unitprice, Double currentqty, Integer status, Set fuelstockHasUsers, Set invoices) {
       this.fueltype = fueltype;
       this.unitprice = unitprice;
       this.currentqty = currentqty;
       this.status = status;
       this.fuelstockHasUsers = fuelstockHasUsers;
       this.invoices = invoices;
    }
   
    public Integer getIdfuel() {
        return this.idfuel;
    }
    
    public void setIdfuel(Integer idfuel) {
        this.idfuel = idfuel;
    }
    public Integer getFueltype() {
        return this.fueltype;
    }
    
    public void setFueltype(Integer fueltype) {
        this.fueltype = fueltype;
    }
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }
    public Double getCurrentqty() {
        return this.currentqty;
    }
    
    public void setCurrentqty(Double currentqty) {
        this.currentqty = currentqty;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getFuelstockHasUsers() {
        return this.fuelstockHasUsers;
    }
    
    public void setFuelstockHasUsers(Set fuelstockHasUsers) {
        this.fuelstockHasUsers = fuelstockHasUsers;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


