package mypojos;
// Generated Aug 12, 2019 9:07:05 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invoiceid;
     private Fuelstock fuelstock;
     private User user;
     private Double qtyintake;
     private Date dateintaken;
     private Double total;
     private Integer paytype;
     private Integer status;

    public Invoice() {
    }

	
    public Invoice(Fuelstock fuelstock, User user) {
        this.fuelstock = fuelstock;
        this.user = user;
    }
    public Invoice(Fuelstock fuelstock, User user, Double qtyintake, Date dateintaken, Double total, Integer paytype, Integer status) {
       this.fuelstock = fuelstock;
       this.user = user;
       this.qtyintake = qtyintake;
       this.dateintaken = dateintaken;
       this.total = total;
       this.paytype = paytype;
       this.status = status;
    }
   
    public Integer getInvoiceid() {
        return this.invoiceid;
    }
    
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }
    public Fuelstock getFuelstock() {
        return this.fuelstock;
    }
    
    public void setFuelstock(Fuelstock fuelstock) {
        this.fuelstock = fuelstock;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getQtyintake() {
        return this.qtyintake;
    }
    
    public void setQtyintake(Double qtyintake) {
        this.qtyintake = qtyintake;
    }
    public Date getDateintaken() {
        return this.dateintaken;
    }
    
    public void setDateintaken(Date dateintaken) {
        this.dateintaken = dateintaken;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Integer getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


