package mypojos;
// Generated Aug 12, 2019 9:07:05 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Salary generated by hbm2java
 */
public class Salary  implements java.io.Serializable {


     private Integer idsalary;
     private User user;
     private Double othrcount;
     private Double pricepOthr;
     private Double total;
     private Integer status;
     private Date datecreate;

    public Salary() {
    }

	
    public Salary(User user) {
        this.user = user;
    }
    public Salary(User user, Double othrcount, Double pricepOthr, Double total, Integer status, Date datecreate) {
       this.user = user;
       this.othrcount = othrcount;
       this.pricepOthr = pricepOthr;
       this.total = total;
       this.status = status;
       this.datecreate = datecreate;
    }
   
    public Integer getIdsalary() {
        return this.idsalary;
    }
    
    public void setIdsalary(Integer idsalary) {
        this.idsalary = idsalary;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getOthrcount() {
        return this.othrcount;
    }
    
    public void setOthrcount(Double othrcount) {
        this.othrcount = othrcount;
    }
    public Double getPricepOthr() {
        return this.pricepOthr;
    }
    
    public void setPricepOthr(Double pricepOthr) {
        this.pricepOthr = pricepOthr;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDatecreate() {
        return this.datecreate;
    }
    
    public void setDatecreate(Date datecreate) {
        this.datecreate = datecreate;
    }




}


