package mypojos;
// Generated Aug 12, 2019 9:07:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String fname;
     private String lname;
     private String nic;
     private String mobile;
     private String telephone;
     private String address;
     private Double salary;
     private Integer loyaltycard;
     private String discription;
     private Integer status;
     private Integer utypstat;
     private Set salaries = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set fuelstockHasUsers = new HashSet(0);

    public User() {
    }

    public User(String fname, String lname, String nic, String mobile, String telephone, String address, Double salary, Integer loyaltycard, String discription, Integer status, Integer utypstat, Set salaries, Set invoices, Set fuelstockHasUsers) {
       this.fname = fname;
       this.lname = lname;
       this.nic = nic;
       this.mobile = mobile;
       this.telephone = telephone;
       this.address = address;
       this.salary = salary;
       this.loyaltycard = loyaltycard;
       this.discription = discription;
       this.status = status;
       this.utypstat = utypstat;
       this.salaries = salaries;
       this.invoices = invoices;
       this.fuelstockHasUsers = fuelstockHasUsers;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }
    public Integer getLoyaltycard() {
        return this.loyaltycard;
    }
    
    public void setLoyaltycard(Integer loyaltycard) {
        this.loyaltycard = loyaltycard;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getUtypstat() {
        return this.utypstat;
    }
    
    public void setUtypstat(Integer utypstat) {
        this.utypstat = utypstat;
    }
    public Set getSalaries() {
        return this.salaries;
    }
    
    public void setSalaries(Set salaries) {
        this.salaries = salaries;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getFuelstockHasUsers() {
        return this.fuelstockHasUsers;
    }
    
    public void setFuelstockHasUsers(Set fuelstockHasUsers) {
        this.fuelstockHasUsers = fuelstockHasUsers;
    }




}


